FROM node:alpine AS builder

# Create app directory
WORKDIR /app

COPY . .

# Install app dependencies
RUN npm install

ENV NODE_ENV production
RUN npm run build

#production environment
FROM nginx:stable-alpine
COPY --from=builder /app /var/www/app
COPY --from=builder /app/.nginx/nginx.conf /etc/nginx/sites-enabled/default
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
